# Module34 Numpy Assignment

Consider the below code to answer further questions:
```
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

```

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

A1. Yes, there is a difference. ```list_``` is a Python list, while ```array_list``` is a NumPy array.

We can print their data types using the type() function:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Printing data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

A2. We can iterate through both and use type():

In [2]:
# Print data type of each element in list_
print("Data type of each element in list_:")
for elem in list_:
    print(type(elem))

# Print data type of each element in array_list
print("\nData type of each element in array_list:")
for elem in array_list:
    print(type(elem))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

```array_list = np.array(object = list_, dtype = int)```

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Consider the below code to answer further questions:
```
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```


In [3]:
# A3.

array_list = np.array(object=list_, dtype=int)

print("Data type of each element in list_:")
for elem in list_:
    print(type(elem))

print("\nData type of each element in array_list:")
for elem in array_list:
    print(type(elem))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Explanation:

A.) The original ```list_``` still contains strings.

B.) ```array_list``` now contains integers (converted using dtype=int).

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [4]:
# A4.

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Shape of the array
print("Shape of num_array:", num_array.shape)

# Size of the array
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


## Explanation:

A.) Shape (2,3) means 2 rows, 3 columns.

B.) Size 6 means there are 6 elements in total.

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [5]:
# A5.

zero_matrix = np.zeros((3, 3))
print("3×3 Zero Matrix:\n", zero_matrix)


3×3 Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Explanation:

np.zeros((3,3)) creates a 3×3 matrix filled with zeros.

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [6]:
# A6.

identity_matrix = np.eye(5)
print("5×5 Identity Matrix:\n", identity_matrix)


5×5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Explanation:

np.eye(5) creates a 5×5 identity matrix with 1s on the diagonal and 0s elsewhere.

