# Module85 Tensorflow Assignment

Objective: The objective of this assignment is to gain practical experience with fundamental operations in TensorFlow, including creating and manipulating matrices, performing arithmetic operations on tensors, and understanding the difference between TensorFlow constants and variables.

## Part 1: Theoretical Question

1. What are the different data structures used in Tensorflow?. Give some examples.

A1. TensorFlow uses several core data structures to build and manipulate machine learning models:

### 1. Tensors
Primary data structure in TensorFlow (like NumPy arrays but optimized for GPUs/TPUs).

Can be scalars, vectors, matrices, or higher-dimensional arrays.
```
import tensorflow as tf
a = tf.constant([1, 2, 3])  # 1D Tensor
b = tf.constant([[1, 2], [3, 4]])  # 2D Tensor

```

### 2. Variables
Mutable tensors used to hold and update model parameters during training.
```
var = tf.Variable([1.0, 2.0])
```

### 3. Datasets
Efficient input pipeline builder for model training using tf.data.

```
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4])
```

### 4. SparseTensor
Used for representing tensors with a lot of zeros efficiently.

```
sparse = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape= [3, 4])
                                
```

### 5. RaggedTensor
Used for handling non-uniform shaped tensors (e.g., lists of different lengths).

```
ragged = tf.ragged.constant([[1, 2], [3], [4, 5, 6]])
```

2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

A2.
```
Feature           | tf.constant               | tf.Variable
--------------------------------------------------------------------------------------------------
Mutability        | Immutable                 | Mutable (can be updated)

Use Case          | Fixed values(e.g.config)  | Model parameters (weights, biases)

Graph Behavior    | Static                    | Dynamic
```

In [ ]:
import tensorflow as tf

# TensorFlow constant
c = tf.constant(10)
# TensorFlow variable
v = tf.Variable(10)

print("Constant:", c)
print("Variable before update:", v)

# v can be updated
v.assign(20)
print("Variable after update:", v)


3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

A3. TensorFlow supports all standard matrix operations, similar to NumPy but optimized for GPUs.

### Matrix Addition (Element-wise)
```
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
add = tf.add(a, b)  # or a + b
```

###  Matrix Multiplication
```
mul = tf.matmul(a, b)
```

Note: This is matrix multiplication, not element-wise.

### Element-wise Multiplication
```
elementwise = tf.multiply(a, b)  # or a * b
```


In [4]:
# Example Output
import tensorflow as tf

a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
add = tf.add(a, b)                              # or a + b

mul = tf.matmul(a, b)

elementwise = tf.multiply(a, b)                  # or a * b

print("Addition:\n", add.numpy())
print("\nMatrix Multiplication:\n", mul.numpy())
print("\nElement-wise Multiplication:\n", elementwise.numpy())


Addition:
 [[ 6  8]
 [10 12]]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


## Part 2: Practical Implementation

### Task 1: Creating and Manipulating Matrices

1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A.

In [5]:
A = tf.random.normal(shape=(3, 3))
print("Matrix A (3x3 from random_normal):\n", A.numpy())

Matrix A (3x3 from random_normal):
 [[ 0.19110447 -0.15381949 -1.0791095 ]
 [ 1.3910027   0.51991004  1.6966654 ]
 [ 1.2699556   0.33313942  0.36262763]]


2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B.

In [6]:
B = tf.random.truncated_normal(shape=(4, 4))
print("\nMatrix B (4x4 from truncated_normal):\n", B.numpy())


Matrix B (4x4 from truncated_normal):
 [[ 1.7386419   0.10299935 -1.5202519  -1.1427886 ]
 [-1.1204553  -1.1181332   0.40689334 -1.6725258 ]
 [ 0.6682135  -1.4171058  -0.990104    0.9962366 ]
 [-0.6734126   0.3335903  -0.3262748  -1.6268419 ]]


3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

In [7]:
C = tf.random.normal(shape=(2, 2), mean=3.0, stddev=0.5)
print("\nMatrix C (2x2 with mean=3, stddev=0.5):\n", C.numpy())


Matrix C (2x2 with mean=3, stddev=0.5):
 [[3.1117952 3.9030538]
 [2.5168352 2.7949271]]


4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

A4.  Attempting to add matrix A (3x3) and B (4x4) will raise an error due to shape mismatch

To demonstrate matrix addition, let's create compatible shapes instead:


In [8]:
# Optional Fix: Create a new B with same shape as A for demonstration
B_compatible = tf.random.truncated_normal(shape=(3, 3))
D = tf.add(A, B_compatible)
print("\nMatrix D (A + B_compatible):\n", D.numpy())


Matrix D (A + B_compatible):
 [[ 0.20923033 -1.078168    0.3275808 ]
 [ 1.2365003  -0.74078757  0.2619064 ]
 [-0.53423595  0.01466587  0.9583088 ]]


5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [9]:
#Matrix Multiplication: Matrix C (2x2) * Matrix D (for demo, 2x2)
# We'll create a compatible 2x2 D for this

D_compatible = tf.random.normal(shape=(2, 2))
E = tf.matmul(C, D_compatible)
print("\nMatrix E (C x D_compatible):\n", E.numpy())


Matrix E (C x D_compatible):
 [[6.5482593 1.0596771]
 [5.02656   0.8834576]]


## Task 2: Performing Additional Matrix Operation

1. Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function.

In [11]:
import tensorflow as tf

F = tf.random.uniform(shape=(3, 3), minval=0, maxval=10)
print("Matrix F (3x3 from random_uniform):\n", F.numpy())

Matrix F (3x3 from random_uniform):
 [[5.4183207 2.5836813 8.998205 ]
 [4.136801  7.6534414 1.5148282]
 [4.3215704 6.060281  2.6738274]]


2. Calculate the transpose of matrix F and store the result in matrix G.

In [12]:
G = tf.transpose(F)
print("\nMatrix G (Transpose of F):\n", G.numpy())


Matrix G (Transpose of F):
 [[5.4183207 4.136801  4.3215704]
 [2.5836813 7.6534414 6.060281 ]
 [8.998205  1.5148282 2.6738274]]


3. Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [13]:
H = tf.math.exp(F)
print("\nMatrix H (Exponential of F):\n", H.numpy())


Matrix H (Exponential of F):
 [[2.25500107e+02 1.32458105e+01 8.08855322e+03]
 [6.26022224e+01 2.10788721e+03 4.54863977e+00]
 [7.53067932e+01 4.28495728e+02 1.44953432e+01]]


4. Create a matrix I by concatenating matrix F and matrix G horizontally.

In [14]:
I = tf.concat([F, G], axis=1)
print("\nMatrix I (Horizontal concat of F and G):\n", I.numpy())


Matrix I (Horizontal concat of F and G):
 [[5.4183207 2.5836813 8.998205  5.4183207 4.136801  4.3215704]
 [4.136801  7.6534414 1.5148282 2.5836813 7.6534414 6.060281 ]
 [4.3215704 6.060281  2.6738274 8.998205  1.5148282 2.6738274]]


5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [15]:
J = tf.concat([F, H], axis=0)
print("\nMatrix J (Vertical concat of F and H):\n", J.numpy())


Matrix J (Vertical concat of F and H):
 [[5.41832066e+00 2.58368134e+00 8.99820518e+00]
 [4.13680077e+00 7.65344143e+00 1.51482821e+00]
 [4.32157040e+00 6.06028080e+00 2.67382741e+00]
 [2.25500107e+02 1.32458105e+01 8.08855322e+03]
 [6.26022224e+01 2.10788721e+03 4.54863977e+00]
 [7.53067932e+01 4.28495728e+02 1.44953432e+01]]
